# Default GitHub issue data file (YAML)
issuelabel_1: color1: "#ffffff" title1: "wontfix" description1: "This will not be worked on"
issueLabel_2: color2: "#d876e3" title2: "question" description2: "Further information is requested"
issueLabel_3: color3: "#e4e669" title3: "invalid" description3: "This doesn't seem right"
issueLabel_4: color4: "#008672" title4: "help wanted" description4: "Extra attention is needed"
issueLabel_5: color5: "#7057ff" title5: "good first issue" description5: "Good for newcomers"
issueLabel_6: color6: "#a2eeef" title6: "enhancement" description6: "New feature or request"
issueLabel_7: color7: "#cfd3d7" title7: "duplicate" description7: "This issue or pull request already exists"
issueLabel_8: color8: "#0075ca" title8: "documentation" description8: "Improvements or additions to documentation"
issueLabel_9: color9: "#d73a4a" title9: "bug" description9: "Something isn't working"
issueLabel_10: color10: "#006B75" title10: "Bad English" description10: "For problems with the use of wording in English."
issueLabel_11: color11: "#D4C5F9" title11: "Clarification needed" description11: "For if something needs more info"
issueLabel_12: color12: "#FBCA04" title12: "Goal" description12: "For future goals on this project"
issueLabel_13: color13: "#C5DEF5" title13: "Image transparency" description13: "For problems with image transparency"
issueLabel_14: color14: "#F9D0C4" title14: "Link rot" description14: "For issues with link rot/dead links (when a link returns a 404)"
issueLabel_15: color15: "#0052CC" title15: "Markdown syntax problem" description15: "For incorrect Markdown syntax"
issueLabel_16: color16: "#D4C5F9" title16: "Organization info missing" description16: "For if you find the 2 missing organizations (2021)"
issueLabel_17: color17: "#B60205" title17 "Ruby syntax error" description17: "For errors with Ruby syntax."
# Users can also create their own issue labels, and customize the color, title, and description
# issueLabel_18: color18: "#000000" title18: "void" description18: "not yet created"
# No known limit on # of issue labels
# End of file
